name: Go

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:

  build:
    name: test
    runs-on: ubuntu-latest
    steps:
      - name: cache
        uses: actions/cache@v1.1.2
        with:
          key: ${{ runner.os }}-go-${{ hashFiles('**/go.sum') }}
          path: ~/go/pkg/mod
          restore-keys: |
             ${{ runner.os }}-go-

      - name: Set up Go 1.14
        uses: actions/setup-go@v1
        with:
          go-version: 1.14
        id: go

      - name: Check out code into the Go module directory
        uses: actions/checkout@v2

      - name: Test
        run: go test ./...
